# Generated by Django 5.0.4 on 2024-05-04 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('dataset', models.FileField(upload_to='media/dataset', verbose_name='Dataset user')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('status', models.CharField(choices=[('DE', 'Deleted'), ('P', 'Published'), ('D', 'Draft')], default='P', max_length=2, verbose_name='Status')),
                ('categories', models.CharField(choices=[('H', 'HIV'), ('T', 'Tuberculosis'), ('A', 'Airborne'), ('W', 'Waterborne'), ('O', 'Other')], default='H', max_length=1, verbose_name='Categories')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
