# Generated by Django 5.0.4 on 2024-05-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_innovation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
