# Generated by Django 5.0.4 on 2024-05-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_forum_innovation_likes_forumcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Is edited'),
        ),
        migrations.AddField(
            model_name='innovationcomment',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Is edited'),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='likes',
            field=models.IntegerField(blank=True, default=0, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='innovationcomment',
            name='likes',
            field=models.IntegerField(blank=True, default=0, verbose_name='Likes'),
        ),
    ]
