# Generated by Django 5.0.4 on 2024-05-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_forumcomment_is_edited_innovationcomment_is_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='likes',
            field=models.IntegerField(blank=True, default=0, verbose_name='Likes'),
        ),
    ]
