# Generated by Django 5.0.4 on 2024-05-08 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_is_active'),
        ('core', '0005_alter_forumcomment_likes_alter_innovation_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='innovationcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovation_comments', to='accounts.userprofile'),
        ),
    ]
