# Generated by Django 5.0.4 on 2024-05-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_innovation_dataset_innovation_dashboard_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='dashboard_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/dashboards', verbose_name='Dashboard preview'),
        ),
    ]
