# Generated by Django 5.0.4 on 2024-05-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_innovation_dashboard_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovationcomment',
            name='likes',
        ),
        migrations.AddField(
            model_name='innovation',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/dashboards_banners', verbose_name='Dashboard banner image'),
        ),
        migrations.AddField(
            model_name='innovation',
            name='dashboard_definition',
            field=models.FileField(blank=True, null=True, upload_to='media/dashboard_definitions', verbose_name='Dashboard and Dataset files'),
        ),
    ]
