# Generated by Django 5.0.4 on 2024-05-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_innovation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
