# Generated by Django 5.0.4 on 2024-05-11 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_is_updated'),
        ('core', '0011_like_created_at_alter_like_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('innovation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookmarks', to='core.innovation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='accounts.userprofile')),
            ],
        ),
    ]
