# Generated by Django 5.0.4 on 2024-05-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_innovation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovation',
            name='slug',
        ),
    ]
