# Generated by Django 5.0.4 on 2024-05-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='comments_number',
            field=models.IntegerField(blank=True, default=0, verbose_name='Number of comments'),
        ),
        migrations.AddField(
            model_name='innovation',
            name='likes_number',
            field=models.IntegerField(blank=True, default=0, verbose_name='Number of likes'),
        ),
    ]
