# Generated by Django 5.0.4 on 2024-05-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_innovation_comments_number_innovation_likes_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='comments_number',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Number of comments'),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='likes_number',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Number of likes'),
        ),
    ]
