# Generated by Django 5.0.4 on 2024-05-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_innovation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='status',
            field=models.CharField(choices=[('DE', 'Deleted'), ('P', 'Published'), ('D', 'Draft')], default='P', max_length=2, verbose_name='Status'),
        ),
    ]
