# Generated by Django 5.0.4 on 2024-05-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_innovation_comments_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='author',
            new_name='user',
        ),
    ]
