# Generated by Django 5.0.4 on 2024-05-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_innovation_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='dashboards_banners/', verbose_name='Dashboard banner image'),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='dashboard_definition',
            field=models.FileField(blank=True, null=True, upload_to='dashboard_definitions/', verbose_name='Dashboard and Dataset files'),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='dashboard_image',
            field=models.ImageField(blank=True, null=True, upload_to='dashboards/', verbose_name='Dashboard preview'),
        ),
    ]
