# Generated by Django 5.0.4 on 2024-05-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_innovation_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='likes_number',
            field=models.IntegerField(blank=True, default=0, verbose_name='Number of likes'),
        ),
    ]
