# Generated by Django 5.0.4 on 2024-05-23 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_innovation_likes_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='likes_number',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of likes'),
        ),
    ]
