# Generated by Django 5.0.4 on 2024-05-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_innovation_likes_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumcomment',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='forumcomment',
            name='author',
        ),
        migrations.RenameField(
            model_name='innovation',
            old_name='dashboard_definition',
            new_name='dashboard_definitions',
        ),
        migrations.RemoveField(
            model_name='innovation',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='innovation',
            name='category',
        ),
        migrations.AddField(
            model_name='innovation',
            name='dashboard_id',
            field=models.TextField(blank=True, null=True, verbose_name='Dashboard Embed ID'),
        ),
        migrations.AddField(
            model_name='innovation',
            name='dashboard_type',
            field=models.CharField(choices=[('S', 'Superset'), ('M', 'Metabase'), ('P', 'Power BI'), ('O', 'Other')], default='O', max_length=1, verbose_name='Dashboard Type'),
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='ForumComment',
        ),
    ]
