# Generated by Django 5.0.4 on 2024-06-06 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_forumcomment_forum_remove_forumcomment_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innovation',
            old_name='dashboard_id',
            new_name='embded_id',
        ),
    ]
