# Generated by Django 5.0.4 on 2024-06-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_dashboard_id_innovation_embded_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='embded_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Dashboard Embed ID'),
        ),
    ]
