# Generated by Django 5.0.4 on 2024-06-07 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_innovation_embded_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innovation',
            old_name='embded_id',
            new_name='embed_id',
        ),
    ]
