# Generated by Django 5.0.4 on 2024-05-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_mod',
            new_name='is_forum_mod',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_site_mod',
            field=models.BooleanField(default=False),
        ),
    ]
