# Generated by Django 5.0.4 on 2024-05-01 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customusermodel_options_customusermodel_is_mod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='username',
        ),
    ]
