# Generated by Django 5.0.4 on 2024-05-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_is_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_updated',
        ),
    ]
