# Generated by Django 5.0.4 on 2024-05-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_created_at_userprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linked_in_url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='LinkedIn Profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='superset_url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Superset Profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='x_in_url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='X Profile'),
        ),
    ]
